### user signup
POST localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password",
  "intro": "intro"
}

### Security Test
GET localhost:8080/api/users/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXV0aCI6W10sImV4cCI6MTcyMTgzODczNCwiaWF0IjoxNzIxODM2OTM0fQ.kkzAwk7atQkbTO7ufCzKy0XPOfpsbfYkhKVBMcd26xU0IKniUMyqxDNERreffSqROHNF0dPyyEJ4NEGhKUSwaA