### create verification code
POST localhost:8080/api/users/verify/email
Content-Type: application/json

{
  "email": "test@test12321.com"
}

### user activate
POST localhost:8080/api/users/verify/792960
Content-Type: application/json

{
  "email": "test@test12321.com"
}

### user signup
POST localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "test@test12321.com",
  "username":"이름",
  "password": "password",
  "intro": "intro"
}

### Security Test
GET localhost:8080/api/users/test
Content-Type: application/json
Authorization: Bearer

### get user profile
GET localhost:8080/api/users/profile
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### update user profile
PUT localhost:8080/api/users/profile
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "newUsername",
  "intro": "newIntro"
}

### change user password
PUT localhost:8080/api/users/password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "password": "password",
  "newPassword": "newPassword"
}

### find user id
POST localhost:8080/api/users/find/id
Content-Type: application/json

{
  "email": "test@test123.com"
}

### find password and send verification code to user
POST localhost:8080/api/users/find/password
Content-Type: application/json

{
  "email": "dkssud0257@naver.com"
}

> {%
    client.global.set("uuid", response.body)
%}

### verify verification code
POST localhost:8080/api/users/verify/{{uuid}}/767512

### change password
PUT localhost:8080/api/users/change/password/68205915-ea61-4901-afc8-ee195f159e0e
Content-Type: application/json

{
  "email": "dkssud0257@naver.com",
  "newPassword": "password123"
}
