name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 리포지토리의 콘텐츠에 대한 읽기 권한

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # JDK 21
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  # gradlew에 실행 권한을 부여

      # Gradle 빌드 및 테스트 실행
      - name: Build and Test with Gradle
        run: ./gradlew clean build test  # 빌드와 테스트를 한 번에 실행
